version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    tty: true
  web:
    build: .
    ports:
     - 80:80
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: on-failure